server:
  port: 9000

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty
  mail:
    host: smtp.gmail.com
    port: 587
    username: cshubstore@gmail.com
    password: pxfzzqfsaszshymt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  user:
    name: admin
    password: root

merchstore:
  app:
    jwtSecret: $2a$10$ybpVe8oMXDNH8o63lez.NOB5dDXX4JCKvSCzQryyTI1u4M5gLzH3C
    jwtExpirationMs: 1800000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
  file: app.log


  